/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
/* Header for class com_example_reinforce_shell_JniBridge */

#ifndef _Included_com_example_reinforce_shell_JniBridge
#define _Included_com_example_reinforce_shell_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_reinforce_shell_JniBridge
 * Method:    init
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_reinforce_shell_SdkShell_init
        (JNIEnv *, jclass , jobject,jobject);

#ifdef __cplusplus
}
#endif
#endif